"""added token table

Revision ID: 316275fa7839
Revises: ac683e408e19
Create Date: 2026-08-25 11:16:43.512216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '316275fa7839'
down_revision: Union[str, Sequence[str], None] = 'ac683e408e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('end_user_id', sa.Integer(), nullable=True),
    sa.Column('token_hashed', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.ForeignKeyConstraint(['end_user_id'], ['end_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_developer_id'), 'tokens', ['developer_id'], unique=False)
    op.create_index(op.f('ix_tokens_end_user_id'), 'tokens', ['end_user_id'], unique=False)
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_end_user_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_developer_id'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
