"""cascade

Revision ID: 340bb07815bb
Revises: 4112d27d1478
Create Date: 2026-08-25 12:40:23.710007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '340bb07815bb'
down_revision: Union[str, Sequence[str], None] = '4112d27d1478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tokens_developer_id_fkey'), 'tokens', type_='foreignkey')
    op.create_foreign_key(None, 'tokens', 'developers', ['developer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.create_foreign_key(op.f('tokens_developer_id_fkey'), 'tokens', 'developers', ['developer_id'], ['id'])
    # ### end Alembic commands ###
