"""cascade

Revision ID: 4112d27d1478
Revises: b8606fddd3de
Create Date: 2026-08-25 12:27:07.906198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4112d27d1478'
down_revision: Union[str, Sequence[str], None] = 'b8606fddd3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tokens_end_user_id_fkey'), 'tokens', type_='foreignkey')
    op.create_foreign_key(None, 'tokens', 'end_users', ['end_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.create_foreign_key(op.f('tokens_end_user_id_fkey'), 'tokens', 'end_users', ['end_user_id'], ['id'])
    # ### end Alembic commands ###
