"""added cascasde to foreign key

Revision ID: 7b873b9a3697
Revises: a3bf447876fe
Create Date: 2026-08-24 09:01:45.899975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b873b9a3697'
down_revision: Union[str, Sequence[str], None] = 'a3bf447876fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('projects_developer_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'developers', ['developer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_developer_id_fkey'), 'projects', 'developers', ['developer_id'], ['id'])
    # ### end Alembic commands ###
