"""initial database

Revision ID: a368b3a8f6ed
Revises: 
Create Date: 2026-09-17 00:02:11.104267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a368b3a8f6ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developers_email'), 'developers', ['email'], unique=True)
    op.create_index(op.f('ix_developers_id'), 'developers', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('api', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_api'), 'projects', ['api'], unique=True)
    op.create_index(op.f('ix_projects_developer_id'), 'projects', ['developer_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('end_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_end_hashedpass', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'email', name='project_user_unique')
    )
    op.create_index(op.f('ix_end_users_email'), 'end_users', ['email'], unique=False)
    op.create_index(op.f('ix_end_users_id'), 'end_users', ['id'], unique=False)
    op.create_index(op.f('ix_end_users_project_id'), 'end_users', ['project_id'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('end_user_id', sa.Integer(), nullable=True),
    sa.Column('token_hashed', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['end_user_id'], ['end_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_developer_id'), 'tokens', ['developer_id'], unique=False)
    op.create_index(op.f('ix_tokens_end_user_id'), 'tokens', ['end_user_id'], unique=False)
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_index(op.f('ix_tokens_token_hashed'), 'tokens', ['token_hashed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_token_hashed'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_end_user_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_developer_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_end_users_project_id'), table_name='end_users')
    op.drop_index(op.f('ix_end_users_id'), table_name='end_users')
    op.drop_index(op.f('ix_end_users_email'), table_name='end_users')
    op.drop_table('end_users')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_developer_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_api'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_developers_id'), table_name='developers')
    op.drop_index(op.f('ix_developers_email'), table_name='developers')
    op.drop_table('developers')
    # ### end Alembic commands ###
