"""Phase1 complete schemas

Revision ID: a3bf447876fe
Revises: 74b654eadc29
Create Date: 2026-08-20 09:50:28.613583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a3bf447876fe'
down_revision: Union[str, Sequence[str], None] = '74b654eadc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('end_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_end_hashedpass', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_end_users_email'), 'end_users', ['email'], unique=True)
    op.create_index(op.f('ix_end_users_id'), 'end_users', ['id'], unique=False)
    op.create_index(op.f('ix_end_users_project_id'), 'end_users', ['project_id'], unique=False)
    op.add_column('developers', sa.Column('verified', sa.Boolean(), nullable=False))
    op.drop_column('developers', 'verfified')
    op.add_column('projects', sa.Column('hashed_api', sa.String(), nullable=False))
    op.create_index(op.f('ix_projects_hashed_api'), 'projects', ['hashed_api'], unique=True)
    op.drop_column('projects', 'enviroment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('enviroment', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_projects_hashed_api'), table_name='projects')
    op.drop_column('projects', 'hashed_api')
    op.add_column('developers', sa.Column('verfified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('developers', 'verified')
    op.drop_index(op.f('ix_end_users_project_id'), table_name='end_users')
    op.drop_index(op.f('ix_end_users_id'), table_name='end_users')
    op.drop_index(op.f('ix_end_users_email'), table_name='end_users')
    op.drop_table('end_users')
    # ### end Alembic commands ###
