"""removed hashed api using plain

Revision ID: ac683e408e19
Revises: 7b873b9a3697
Create Date: 2026-08-24 09:48:28.518066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac683e408e19'
down_revision: Union[str, Sequence[str], None] = '7b873b9a3697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('api', sa.String(), nullable=False))
    op.drop_index(op.f('ix_projects_hashed_api'), table_name='projects')
    op.create_index(op.f('ix_projects_api'), 'projects', ['api'], unique=True)
    op.drop_column('projects', 'hashed_api')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('hashed_api', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_projects_api'), table_name='projects')
    op.create_index(op.f('ix_projects_hashed_api'), 'projects', ['hashed_api'], unique=True)
    op.drop_column('projects', 'api')
    # ### end Alembic commands ###
