"""added index to hashed token

Revision ID: b8606fddd3de
Revises: 316275fa7839
Create Date: 2026-08-25 11:19:02.176262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8606fddd3de'
down_revision: Union[str, Sequence[str], None] = '316275fa7839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tokens_token_hashed'), 'tokens', ['token_hashed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_token_hashed'), table_name='tokens')
    # ### end Alembic commands ###
