"""added unique constraint

Revision ID: e9058e82fe4f
Revises: 00d024a58ab9
Create Date: 2026-09-03 21:19:44.518980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e9058e82fe4f'
down_revision: Union[str, Sequence[str], None] = '00d024a58ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('end_users', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_end_users_email'), table_name='end_users')
    op.create_index(op.f('ix_end_users_email'), 'end_users', ['email'], unique=False)
    op.create_unique_constraint('project_user_unique', 'end_users', ['project_id', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_user_unique', 'end_users', type_='unique')
    op.drop_index(op.f('ix_end_users_email'), table_name='end_users')
    op.create_index(op.f('ix_end_users_email'), 'end_users', ['email'], unique=True)
    op.alter_column('end_users', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
